export default [
  {
    path: '/user',
    layout: false,
    routes: [{ name: 'Login', path: '/user/login', component: './user/login' }],
  },
  {
    path: '/',
    name: 'Welcome',
    component: './landing',
    layout: false,
  },
  {
    path: '/landing',
    name: 'Welcome',
    component: './landing',
    layout: false,
    hideInMenu: true,
  },
  { 
    path: '/home', 
    name: 'Home', 
    icon: 'home', 
    component: './home' 
  },
  {
    path: '/pricing',
    name: 'Pricing',
    icon: 'dollar',
    component: './pricing',
    layout: false,
  },
  {
    path: '/video-generation',
    name: 'Create Video',
    icon: 'videoCameraAdd',
    component: './video-generation',
    hideInMenu: true,
  },
  {
    path: '/long-video',
    name: 'Long Video Studio',
    icon: 'playCircle',
    component: './long-video',
    hideInMenu: true,
  },
  {
    path: '/image-generation',
    name: 'Create Image',
    icon: 'picture',
    component: './image-generation',
    hideInMenu: true,
  },
  {
    path: '/tasks',
    name: 'My Creations',
    icon: 'playCircle',
    component: './tasks',
  },
  {
    path: '/organisation',
    name: 'Organisation',
    icon: 'table',
    component: './organisation',
    access: 'canAdmin',
  },
  {
    path: '/billing',
    name: 'Billing',
    icon: 'dollarCircle',
    component: './billing',
    access: 'canAdmin',
  },
  {
    path: '/admin-feedback',
    name: 'Feedback Management',
    icon: 'star',
    component: './admin-feedback',
    access: 'canAdmin',
  },
  { component: '404', layout: false, path: './*' },
];
