"""remove_organization_id_from_user_service

Revision ID: 0c138e1c7cbd
Revises: 7aadd7dd1cda
Create Date: 2025-08-05 21:22:10.552917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c138e1c7cbd'
down_revision: Union[str, Sequence[str], None] = '7aadd7dd1cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_services_organization_id_fkey'), 'user_services', type_='foreignkey')
    op.drop_column('user_services', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_services', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_services_organization_id_fkey'), 'user_services', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
