"""Add creation_tasks table

Revision ID: 235ebbe63461
Revises: 263452264c7b
Create Date: 2025-08-03 13:42:28.440586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235ebbe63461'
down_revision: Union[str, Sequence[str], None] = '263452264c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creation_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('VIDEO', 'IMAGE', 'AUDIO', 'TEXT', 'MODEL_3D', name='assettype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_assets', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creation_tasks_id'), 'creation_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_creation_tasks_status'), 'creation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_creation_tasks_task_type'), 'creation_tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creation_tasks_task_type'), table_name='creation_tasks')
    op.drop_index(op.f('ix_creation_tasks_status'), table_name='creation_tasks')
    op.drop_index(op.f('ix_creation_tasks_id'), table_name='creation_tasks')
    op.drop_table('creation_tasks')
    # ### end Alembic commands ###
