"""make_organization_id_nullable_and_add_name_column

Revision ID: 263452264c7b
Revises: c12ab73da49e
Create Date: 2025-08-02 14:25:04.755970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263452264c7b'
down_revision: Union[str, Sequence[str], None] = 'c12ab73da49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
