"""Add local video and thumbnail URL columns

Revision ID: 4d2b8f532feb
Revises: 235ebbe63461
Create Date: 2025-08-03 15:12:42.006205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2b8f532feb'
down_revision: Union[str, Sequence[str], None] = '235ebbe63461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creation_tasks', sa.Column('local_video_url', sa.String(), nullable=True))
    op.add_column('creation_tasks', sa.Column('local_thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creation_tasks', 'local_thumbnail_url')
    op.drop_column('creation_tasks', 'local_video_url')
    # ### end Alembic commands ###
