"""add_services_table_and_update_creation_tasks

Revision ID: 9c77907f2506
Revises: 4d2b8f532feb
Create Date: 2025-08-03 15:46:49.081743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c77907f2506'
down_revision: Union[str, Sequence[str], None] = '4d2b8f532feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_per_generation', sa.Float(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.add_column('creation_tasks', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'creation_tasks', 'services', ['service_id'], ['id'])
    op.drop_column('creation_tasks', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creation_tasks', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'creation_tasks', type_='foreignkey')
    op.drop_column('creation_tasks', 'service_id')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
